server:
  port: 8080
spring:
  datasource:
    username: *
    password: *
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

indexing-settings:
  sites:
    - url: https://volochek.life
      name: Вышний волочек
    - url: https://nikoartgallery.com
      name: Креативное пространство и галерея Н.Б. Никогосяна
    - url: https://et-cetera.ru/mobile
      name: Ет Сетера Мобайл

logging:
  level:
    org.springframework.aop.framework.JdkDynamicAopProxy: ERROR
    searchengine.services.impl.scraper: DEBUG