# example values

index-config:
# Данная структура в Java превращается в Map<String, String>, где ключ это url
# а значение name
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru