server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/search_engine?reWriteBatchedInserts=true
    username: search
    password: *
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC

indexing-settings:
  sites:
    - url: https://volochek.life
      name: Вышний волочек
    - url: https://nikoartgallery.com
      name: Креативное пространство и галерея Н.Б. Никогосяна
    - url: https://et-cetera.ru/mobile
      name: Ет Сетера Мобайл

logging:
  level:
    org.springframework.aop.framework.JdkDynamicAopProxy: ERROR
    searchengine.services.impl.scraper: DEBUG